### ISSUE TITLE
Building paperback results only in "Hello world!"

### ISSUE THREAD

**Issue by Tunas1337** [cyphar/paperback#2]
I'm unsure if this is still a work-in-progress, but when I read the design document, it seemed pretty finished.
Am I doing something wrong, or does building it result in an executable that just says "hello world"?

**Comment by cyphar** [comment]
This is still a work-in-progress project (and the "binary" output is just the sample Rust program you get with `cargo new`).

I wrote out the design document to make sure the design made sense before I wrote any code. Right now, I have a fair amount of the core code written (but not yet committed because I'm not happy with the library design), but I'm currently on vacation and won't be working on it until I get back home. The PDF generation will probably end up being the most annoying thing to get working though (the mockups were made in Inkscape).

**Comment by cyphar** [comment]
I've added a note to the README to mention this is still a work-in-progress project. I hope to have the initial implementation done in a month or so (this is a side project so I can only really work on it when I have time).

**Comment by Tunas1337** [comment]
Ah, I see. Though it would be nice to at least push the code you wrote to a different branch (experimental, for example), no worries, take your time and have a nice vacation!

**Comment by cyphar** [comment]
776f66b4e0508f5d451d3a323bc2f5bca7f5a9bc is an implementation of the core of paperback. Document generation is still a WIP. I do have some mockups now of what they'll look like in the README, but I'm still not quite sure how I'll do the PDF generation.

**Comment by cyphar** [comment]
@Tunas1337 If you're still interested in this project, paperback now is pretty much fully functional (sorry for the long wait -- there wasn't any good PDF generating libraries in rust that had all the features I needed in 2020).

You can create backups with `paperback backup` and then restore or expand with the respective subcommands. At the moment paperback cannot scan the QR codes for you, so you need to figure out how to scan the main document codes (you can copy-paste the backup codes).

**Comment by Tunas1337** [comment]
Holy cow, it has come a long way indeed! Thank you for the heads-up to take another look at the project :D

I'll close this issue because it is no longer relevant.
